'use client';
import { sitePath } from '@/lib/site-path';

import {useState} from 'react';
const reviews=[
{author:'Annie T. - Dublin, CA',text:'"DO-NUTS!!! Love this little mom and pop shop! The donuts are consistently delicious. They close their doors when they’re sold out for the day, so I try to get there early. I also like that they’re peanut-free, which makes it safe for my family to eat at. There is a large seating area indoors, which is a surprise, though I’ve always taken my box of goodies to go. (This way no one will judge me when I shove multiple donuts into my mouth in an impressively short span of time! Haha)"'},
{author:'Diana M. - Dublin, CA',text:'"Honestly, the best donuts I’ve had in a long time. You cannot go wrong with their glazed. So soft and not overly sweet. This spot actually has lemon-filled donuts as well. I also like their apple fritters and their crullers! Writing about this makes me want to go back for more!"'},
{author:'Anthony V. - Dublin, CA',text:'"Great donut spot! Went in at around 8am and they still had a full selection. Donuts are cooked to perfection (at least for my tastes). Not too oily or over fried, not too sweet (like a certain donut chain), and not too heavy. They fill with custard on demand, put in a good amount, and the flavor is really good."'},
{author:'Mary Grace T. - Dublin, CA',text:"\"I love these donuts so much. I ordered them for my kids’ birthdays. They’re light, fluffy, chewy, and so fresh! It’s no frills and the prices are amazing for how big the donuts are. My favorites are the apple fritters, sugar, glazed, maple bars, and buttermilk donuts..... ugh so good! Best donuts in the Tri-Valley!\""}
];
export default function Reviews(){const [index,setIndex]=useState(0);return <section className="reviews" aria-label="Customer testimonials"><div className="review-sources"><a href="https://www.yelp.com/biz/johnnys-donuts-dublin" aria-label="Read reviews on Yelp"><img src={sitePath("/assets/bec1dd_88e711b2f10b45c081944369af1923cc~mv2.png")} alt="Yelp"/></a><a href="https://www.google.com/search?q=johnnys+donuts+dublin+california" aria-label="Read reviews on Google"><img src={sitePath("/assets/bec1dd_db0d059c2fee4701a3513350ddd1ffe0~mv2.jpg")} alt="Google"/></a></div><div aria-live="polite"><p className="review-author">{reviews[index].author}</p><blockquote>{reviews[index].text}</blockquote></div><button className="arrow previous" aria-label="Previous testimonial" onClick={()=>setIndex((index+reviews.length-1)%reviews.length)}>‹</button><button className="arrow next" aria-label="Next testimonial" onClick={()=>setIndex((index+1)%reviews.length)}>›</button><div className="review-dots">{reviews.map((r,i)=><button key={r.author} aria-label={`Review ${i+1}`} aria-current={index===i?'true':undefined} onClick={()=>setIndex(i)}/>)}</div></section>}
